#!/usr/bin/env python3
"""
Select a patient-complete subcohort aligned to the treatment-context drug project.

Selection is done at the patient level, then all cleaned visits and notes for the
selected patients are retained. This keeps longitudinal context intact while
bounding corpus size.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, List

import pandas as pd


DEFAULT_CLINIC_TYPES = [
    "Progress Notes",
    "Assessment & Plan Note",
    "Patient Instructions",
    "H&P",
    "H&P (View-Only)",
    "Research Coordinator Notes",
    "Consults",
    "Discharge Instructions",
]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Select patient-complete treatment-context subcohort.")
    p.add_argument(
        "--full-visit-manifest",
        default="episode_notes/manifests/full_visit_eligible_manifest.csv",
        help="Full eligible visit manifest generated by run_select_note_corpus.py",
    )
    p.add_argument("--notes-dir", default="episode_notes", help="Directory containing episode_notes_chunk*.parquet")
    p.add_argument("--glob", default="episode_notes_chunk*.parquet", help="Glob for raw note parquet files.")
    p.add_argument(
        "--note-text-col-candidates",
        default="note_text_full,full_note_text,note_text,text",
        help="Comma-separated note text columns to try in order.",
    )
    p.add_argument("--min-note-chars", type=int, default=20, help="Minimum note length after cleaning.")
    p.add_argument(
        "--clinic-note-types",
        default="|".join(DEFAULT_CLINIC_TYPES),
        help="Pipe-delimited note_title values treated as clinic-like for alignment scoring.",
    )
    p.add_argument("--min-visits-per-patient", type=int, default=8, help="Minimum eligible visits per patient.")
    p.add_argument("--max-visits-per-patient", type=int, default=25, help="Maximum eligible visits per patient.")
    p.add_argument(
        "--min-clinic-candidate-visits",
        type=int,
        default=3,
        help="Minimum clinic-like visits with >=1 candidate span.",
    )
    p.add_argument(
        "--min-clinic-candidate-ratio",
        type=float,
        default=0.20,
        help="Minimum ratio of clinic-like candidate visits to all eligible visits.",
    )
    p.add_argument(
        "--output-dir",
        default="episode_notes/subcohort_patient_complete",
        help="Directory to write selected patient/visit/note manifests.",
    )
    p.add_argument(
        "--write-notes-parquet",
        action="store_true",
        help="If set, write selected cleaned note payload parquet.",
    )
    return p.parse_args()


def _resolve_note_text_col(df: pd.DataFrame, candidates: Iterable[str]) -> str:
    for c in candidates:
        if c in df.columns:
            return c
    raise ValueError(f"No note text column found. Tried: {list(candidates)}")


def _normalize_note_type(series: pd.Series) -> pd.Series:
    return series.fillna("").astype(str).str.strip().replace({"": "<UNKNOWN_NOTE_TYPE>"})


def _clean_selected_notes(
    notes_dir: Path,
    glob_pattern: str,
    selected_patients: set[int],
    note_text_col_candidates: List[str],
    min_note_chars: int,
) -> pd.DataFrame:
    files = sorted(notes_dir.glob(glob_pattern))
    if not files:
        raise FileNotFoundError(f"No files matched: {notes_dir / glob_pattern}")

    frames = []
    for p in files:
        df = pd.read_parquet(p)
        note_text_col = _resolve_note_text_col(df, note_text_col_candidates)
        keep_cols = [
            c
            for c in ["TaskIDNumber", "person_id", "visit_occurrence_id", "note_id", "note_title", "note_date", "note_datetime"]
            if c in df.columns
        ]
        chunk = df[keep_cols].copy()
        chunk["note_text"] = df[note_text_col]
        chunk["source_note_text_col"] = note_text_col
        chunk["person_id"] = pd.to_numeric(chunk["person_id"], errors="coerce").astype("Int64")
        chunk["visit_occurrence_id"] = pd.to_numeric(chunk["visit_occurrence_id"], errors="coerce").astype("Int64")
        chunk = chunk[chunk["person_id"].isin(selected_patients)].copy()
        frames.append(chunk)

    all_notes = pd.concat(frames, ignore_index=True)
    all_notes["note_text"] = all_notes["note_text"].fillna("").astype(str)
    all_notes["note_len"] = all_notes["note_text"].str.len()
    if "note_title" not in all_notes.columns:
        all_notes["note_title"] = "<UNKNOWN_NOTE_TYPE>"
    all_notes["note_title_norm"] = _normalize_note_type(all_notes["note_title"])

    work = all_notes.dropna(subset=["person_id", "visit_occurrence_id", "note_id"]).copy()
    work = work[work["note_text"].str.strip() != ""].copy()
    work = work[work["note_len"] >= min_note_chars].copy()

    sort_cols = [c for c in ["note_datetime", "note_date"] if c in work.columns]
    if sort_cols:
        work = work.sort_values(sort_cols)
    work = work.drop_duplicates(subset=["note_id"], keep="last").copy()

    work["note_text_norm"] = work["note_text"].str.strip().str.lower().str.replace(r"\s+", " ", regex=True)
    work = work.drop_duplicates(subset=["person_id", "visit_occurrence_id", "note_text_norm"], keep="first").copy()
    return work


def main() -> int:
    args = parse_args()
    full_visit_path = Path(args.full_visit_manifest)
    notes_dir = Path(args.notes_dir)
    out_dir = Path(args.output_dir)

    if not full_visit_path.exists():
        raise FileNotFoundError(f"Missing full visit manifest: {full_visit_path}")

    clinic_types = [x.strip() for x in str(args.clinic_note_types).split("|") if x.strip()]
    note_text_col_candidates = [x.strip() for x in str(args.note_text_col_candidates).split(",") if x.strip()]

    visits = pd.read_csv(full_visit_path)
    visits["person_id"] = pd.to_numeric(visits["person_id"], errors="coerce").astype("Int64")
    visits["visit_occurrence_id"] = pd.to_numeric(visits["visit_occurrence_id"], errors="coerce").astype("Int64")
    visits["note_type_mode"] = visits["note_type_mode"].fillna("<UNKNOWN_NOTE_TYPE>").astype(str)
    visits["is_clinic_like_visit"] = visits["note_type_mode"].isin(set(clinic_types))
    visits["has_clinic_candidate"] = visits["has_candidate_span"].astype(bool) & visits["is_clinic_like_visit"]

    patient_df = (
        visits.groupby("person_id", as_index=False)
        .agg(
            eligible_visit_count=("visit_occurrence_id", "nunique"),
            eligible_note_count=("eligible_note_count", "sum"),
            clinic_like_visit_count=("is_clinic_like_visit", "sum"),
            clinic_candidate_visit_count=("has_clinic_candidate", "sum"),
            any_candidate_visit_count=("has_candidate_span", "sum"),
            structured_drug_visit_count=("has_structured_drug_data", "sum"),
            candidate_span_count=("candidate_span_count", "sum"),
            median_notes_per_visit=("eligible_note_count", "median"),
        )
        .copy()
    )
    patient_df["clinic_candidate_visit_ratio"] = (
        patient_df["clinic_candidate_visit_count"] / patient_df["eligible_visit_count"]
    )
    patient_df["clinic_like_visit_ratio"] = (
        patient_df["clinic_like_visit_count"] / patient_df["eligible_visit_count"]
    )

    selected_patients = patient_df[
        patient_df["eligible_visit_count"].between(args.min_visits_per_patient, args.max_visits_per_patient)
        & (patient_df["clinic_candidate_visit_count"] >= args.min_clinic_candidate_visits)
        & (patient_df["clinic_candidate_visit_ratio"] >= float(args.min_clinic_candidate_ratio))
    ].copy()
    selected_patients["selection_rule"] = (
        f"visits_{args.min_visits_per_patient}_{args.max_visits_per_patient}"
        f"__clinic_candidate_visits_ge_{args.min_clinic_candidate_visits}"
        f"__clinic_candidate_ratio_ge_{args.min_clinic_candidate_ratio:.2f}"
    )

    selected_ids = set(int(x) for x in selected_patients["person_id"].dropna().tolist())
    selected_visits = visits[visits["person_id"].isin(selected_ids)].copy()
    selected_notes = _clean_selected_notes(
        notes_dir=notes_dir,
        glob_pattern=args.glob,
        selected_patients=selected_ids,
        note_text_col_candidates=note_text_col_candidates,
        min_note_chars=max(int(args.min_note_chars), 1),
    )
    selected_notes["is_clinic_like_note"] = selected_notes["note_title_norm"].isin(set(clinic_types))

    note_count_by_patient = (
        selected_notes.groupby("person_id", as_index=False)
        .agg(
            selected_note_count=("note_id", "nunique"),
            selected_clinic_like_note_count=("is_clinic_like_note", "sum"),
        )
        .copy()
    )
    selected_patients = selected_patients.merge(note_count_by_patient, on="person_id", how="left")
    selected_patients["selected_note_count"] = selected_patients["selected_note_count"].fillna(0).astype(int)
    selected_patients["selected_clinic_like_note_count"] = (
        selected_patients["selected_clinic_like_note_count"].fillna(0).astype(int)
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    patient_path = out_dir / "patient_manifest.csv"
    visit_path = out_dir / "visit_manifest.csv"
    note_path = out_dir / "note_manifest.csv"
    summary_path = out_dir / "summary.json"
    notes_parquet_path = out_dir / "notes.parquet"

    selected_patients = selected_patients.sort_values(["eligible_visit_count", "selected_note_count", "person_id"], ascending=[True, True, True])
    selected_visits = selected_visits.sort_values(["person_id", "visit_occurrence_id"])
    selected_note_manifest = selected_notes[
        [
            "person_id",
            "visit_occurrence_id",
            "note_id",
            "note_title_norm",
            "note_len",
            "is_clinic_like_note",
        ]
    ].copy().sort_values(["person_id", "visit_occurrence_id", "note_id"])

    selected_patients.to_csv(patient_path, index=False)
    selected_visits.to_csv(visit_path, index=False)
    selected_note_manifest.to_csv(note_path, index=False)
    if args.write_notes_parquet:
        note_cols = [
            c
            for c in [
                "TaskIDNumber",
                "person_id",
                "visit_occurrence_id",
                "note_id",
                "note_date",
                "note_datetime",
                "note_title",
                "note_title_norm",
                "note_len",
                "note_text",
                "source_note_text_col",
                "is_clinic_like_note",
            ]
            if c in selected_notes.columns
        ]
        selected_notes[note_cols].drop_duplicates(subset=["note_id"]).to_parquet(notes_parquet_path, index=False)

    note_type_counts = selected_note_manifest["note_title_norm"].value_counts().head(20).to_dict()
    clinic_note_type_counts = (
        selected_note_manifest[selected_note_manifest["is_clinic_like_note"]]["note_title_norm"].value_counts().head(20).to_dict()
    )

    summary = {
        "selection_goal": "patient_complete_treatment_context_subcohort",
        "selection_reasoning": {
            "patient_complete": True,
            "notes_target": "20k_to_30k_total_cleaned_notes",
            "exclude_too_few_visits": args.min_visits_per_patient,
            "exclude_too_many_visits": args.max_visits_per_patient,
            "require_repeated_clinic_treatment_context": args.min_clinic_candidate_visits,
            "min_clinic_candidate_ratio": float(args.min_clinic_candidate_ratio),
            "clinic_note_types": clinic_types,
            "structured_ehr_not_required_for_selection": True,
        },
        "selection_rule": selected_patients["selection_rule"].iat[0] if len(selected_patients) else None,
        "selected_patients": int(len(selected_patients)),
        "selected_visits": int(len(selected_visits)),
        "selected_notes": int(selected_note_manifest["note_id"].nunique()),
        "selected_clinic_like_notes": int(selected_note_manifest["is_clinic_like_note"].sum()),
        "selected_non_clinic_like_notes": int((~selected_note_manifest["is_clinic_like_note"]).sum()),
        "selected_structured_drug_visits": int(selected_visits["has_structured_drug_data"].sum()),
        "selected_candidate_visits_any": int(selected_visits["has_candidate_span"].sum()),
        "selected_clinic_candidate_visits": int(selected_visits["has_clinic_candidate"].sum()),
        "selected_note_type_top20": note_type_counts,
        "selected_clinic_note_type_top20": clinic_note_type_counts,
        "output_files": {
            "patient_manifest": str(patient_path),
            "visit_manifest": str(visit_path),
            "note_manifest": str(note_path),
            "notes_parquet": str(notes_parquet_path) if args.write_notes_parquet else None,
        },
    }
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("selected_patients", len(selected_patients))
    print("selected_visits", len(selected_visits))
    print("selected_notes", selected_note_manifest["note_id"].nunique())
    print("selected_clinic_like_notes", int(selected_note_manifest["is_clinic_like_note"].sum()))
    print("output_dir", out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
